/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.PharmacyCompanyEnterprise;
import Business.Patient.Patient;
import Business.PharmaceuticalCompany.Drug;
import Business.WorkQueue.FeedbackToPharmaCompanyWorkRequest;
import Business.WorkQueue.PharmacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.PharmaceuticalCompanyRole.ViewDrugGuidelinesJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rekhajindal
 */
public class ManagePatientPharmacyWorkRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Patient patient;
    /**
     * Creates new form ManagePharmacyWorkRequestJPanel
     */
    public ManagePatientPharmacyWorkRequestJPanel(JPanel upc,Patient patient) {
        initComponents();
        this.userProcessContainer=upc;
        this.patient=patient;
        populatePharmacyWorkRequesttable();
        hideControls();
    }

    public void hideControls()
    {
        txtMessage.setVisible(false);
        lblMessage.setVisible(false);
        btnSendRequest.setVisible(false);
        lblDrugID.setVisible(false);
        lblDrugName.setVisible(false);
        lbltxtDrugID.setVisible(false);
        lbltxtDrugName.setVisible(false);
    }
    public void populatePharmacyWorkRequesttable()
    {
        DefaultTableModel model=(DefaultTableModel)PharmacyWorkRequestTable.getModel();
        model.setRowCount(0);
        for(WorkRequest request:patient.getWorkQueue().getWorkRequestList())
        {
            if(request instanceof PharmacyWorkRequest)
            {
                PharmacyWorkRequest phrequest=(PharmacyWorkRequest)request;
                Object[]row=new Object[5];
                row[0]=phrequest;
                row[1]=phrequest.getDoctor().getFirstName();
                row[2]=phrequest.getEnterprise().getName();
                row[3]=phrequest.getDrugSender();
                row[4]=phrequest.getStatus();
                model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PharmacyWorkRequestTable = new javax.swing.JTable();
        btnViewDrugGuidelines = new javax.swing.JButton();
        btnfeedback = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnSendRequest = new javax.swing.JButton();
        btnViewdrug = new javax.swing.JButton();
        lblDrugID = new javax.swing.JLabel();
        lblDrugName = new javax.swing.JLabel();
        lbltxtDrugID = new javax.swing.JLabel();
        lbltxtDrugName = new javax.swing.JLabel();

        jLabel1.setText("List of Pharmacy Work Request");

        PharmacyWorkRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Doctor", "Enterprise Name", "pharmacy Name", "Request Status"
            }
        ));
        jScrollPane1.setViewportView(PharmacyWorkRequestTable);

        btnViewDrugGuidelines.setText("View Drug Guidelines");
        btnViewDrugGuidelines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDrugGuidelinesActionPerformed(evt);
            }
        });

        btnfeedback.setText("Feedback to Pharmaceutical Company");
        btnfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfeedbackActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");

        lblMessage.setText("Message");

        btnSendRequest.setText("Send Request");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });

        btnViewdrug.setText("View Drugs");
        btnViewdrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewdrugActionPerformed(evt);
            }
        });

        lblDrugID.setText("jLabel2");

        lblDrugName.setText("jLabel2");

        lbltxtDrugID.setText("DrugID");

        lbltxtDrugName.setText("Drug Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblMessage)
                        .addGap(33, 33, 33)
                        .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(btnSendRequest)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewdrug, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnViewDrugGuidelines)
                        .addGap(30, 30, 30)
                        .addComponent(btnfeedback)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRefresh)
                                    .addGap(63, 63, 63)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbltxtDrugName)
                                    .addGap(21, 21, 21)
                                    .addComponent(lblDrugName))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbltxtDrugID)
                                    .addGap(21, 21, 21)
                                    .addComponent(lblDrugID))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRefresh)
                        .addGap(27, 27, 27)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfeedback)
                    .addComponent(btnViewDrugGuidelines)
                    .addComponent(btnViewdrug))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrugID)
                    .addComponent(lbltxtDrugID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltxtDrugName)
                    .addComponent(lblDrugName))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMessage)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnSendRequest)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfeedbackActionPerformed
        // TODO add your handling code here:
        int selectedrow=PharmacyWorkRequestTable.getSelectedRow();
        if(selectedrow < 0)
        {
            JOptionPane.showMessageDialog(null, "please select a row");
            return;
        }
        txtMessage.setVisible(true);
        lblMessage.setVisible(true);
        btnSendRequest.setVisible(true);
    }//GEN-LAST:event_btnfeedbackActionPerformed

    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
        // TODO add your handling code here:
        int selectedrow=PharmacyWorkRequestTable.getSelectedRow();
//        if(selectedrow < 0)
//        {
//            JOptionPane.showMessageDialog(null, "please select a row");
//            
//        }
        String message=txtMessage.getText();
        WorkRequest request=(WorkRequest)PharmacyWorkRequestTable.getValueAt(selectedrow, 0);
        PharmacyWorkRequest phRequest=(PharmacyWorkRequest)request;
        Drug drug=phRequest.getSendDrug();
        PharmacyCompanyEnterprise phComEnterprise=(PharmacyCompanyEnterprise)drug.getManufacturingEnterprise();
        
        FeedbackToPharmaCompanyWorkRequest workRequest=new FeedbackToPharmaCompanyWorkRequest();
        workRequest.setMessage(message);
        workRequest.setDrug(drug);
        workRequest.setSender(patient);
        phComEnterprise.getWorkQueue().getWorkRequestList().add(workRequest);
        hideControls();
    }//GEN-LAST:event_btnSendRequestActionPerformed

    private void btnViewDrugGuidelinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDrugGuidelinesActionPerformed
        // TODO add your handling code here:
        int selectedrow=PharmacyWorkRequestTable.getSelectedRow();
        if(selectedrow < 0)
        {
            JOptionPane.showMessageDialog(null, "please select a row");
            return;
        }
        
        WorkRequest request=(WorkRequest)PharmacyWorkRequestTable.getValueAt(selectedrow, 0);
        PharmacyWorkRequest phRequest=(PharmacyWorkRequest)request;
        Drug drug=phRequest.getSendDrug();
        ViewDrugGuidelinesJPanel panel=new ViewDrugGuidelinesJPanel(userProcessContainer, drug);
        userProcessContainer.add("ViewDrugGuidelinesJPanel",panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDrugGuidelinesActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewdrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewdrugActionPerformed
        // TODO add your handling code here:
        lblDrugID.setVisible(true);
        lblDrugName.setVisible(true);
        lbltxtDrugID.setVisible(true);
        lbltxtDrugName.setVisible(true);
        int selectedRow=PharmacyWorkRequestTable.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "please select a row");
            return;
        }
        WorkRequest request=(WorkRequest)PharmacyWorkRequestTable.getValueAt(selectedRow,0);
        PharmacyWorkRequest phRequest=(PharmacyWorkRequest)request;
        Drug drug=phRequest.getSendDrug();
        lblDrugID.setText(String.valueOf(drug.getDrugID()));
        lblDrugName.setText(drug.getDrugName());
        
        
    }//GEN-LAST:event_btnViewdrugActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PharmacyWorkRequestTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JButton btnViewDrugGuidelines;
    private javax.swing.JButton btnViewdrug;
    private javax.swing.JButton btnfeedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDrugID;
    private javax.swing.JLabel lblDrugName;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lbltxtDrugID;
    private javax.swing.JLabel lbltxtDrugName;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
