/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PatientRole;

import Business.EcoSystem;
import Business.Patient.Patient;
import Business.WorkQueue.HospitalEnterpriseAdminWorkRequest;
import Business.WorkQueue.PatientWorkRequest;
import Business.WorkQueue.ReferToOtherDoctorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rekhajindal
 */
public class ManageDoctorWorkRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Patient patient;
    /**
     * Creates new form ManageWorkRequestJPanel
     */
    public ManageDoctorWorkRequestJPanel(JPanel upc,EcoSystem system,Patient patient) {
        initComponents();
        this.userProcessContainer=upc;
        this.system=system;
        this.patient=patient;
        populatePatientWorkRequestTable();
    }

    public void populatePatientWorkRequestTable()
    {
        DefaultTableModel model=(DefaultTableModel)patientWorkRequestTable.getModel();
        model.setRowCount(0);
        for(WorkRequest request:patient.getWorkQueue().getWorkRequestList())
        {
            if(request instanceof HospitalEnterpriseAdminWorkRequest)
            {
                HospitalEnterpriseAdminWorkRequest heRequest=(HospitalEnterpriseAdminWorkRequest)request;
                Object[]row=new Object[5];
                row[0]=heRequest;
                row[1]=heRequest.getDoctor().getFirstName();
                row[2]=heRequest.getEnterpriseSender();
                row[3]=heRequest.getStatus();
                row[4]="Done";
                model.addRow(row);
            }
            if(request instanceof PatientWorkRequest)
            {
                PatientWorkRequest pwRequest=(PatientWorkRequest)request;
                Object[]row=new Object[5];
                row[0]=pwRequest;
                row[1]=pwRequest.getReceiver().getFirstName();
                row[2]=pwRequest.getReceiverEnterprise().getName();
                row[3]=pwRequest.getStatus();
                row[4]=pwRequest.getAppointmentMessage()==null? null: pwRequest.getAppointmentMessage();
                model.addRow(row);
            }
            
            if(request instanceof ReferToOtherDoctorWorkRequest)
            {
                ReferToOtherDoctorWorkRequest referRequest=(ReferToOtherDoctorWorkRequest)request;
                Object[]row=new Object[5];
                row[0]=referRequest;
                row[1]=referRequest.getSender().getFirstName();
                row[2]=referRequest.getSenderEnterprise().getName();
                row[3]=referRequest.getStatus();
                row[4]="N/A";
                model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientWorkRequestTable = new javax.swing.JTable();
        btnCreateNewRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("List of Doctor's Work Requests");

        patientWorkRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Message", "Doctor Name", "Enterprise Name", "Request Status", "Appointment details"
            }
        ));
        jScrollPane1.setViewportView(patientWorkRequestTable);

        btnCreateNewRequest.setText("Create New Request");
        btnCreateNewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewRequestActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnCreateNewRequest)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnCreateNewRequest)
                .addGap(146, 146, 146)
                .addComponent(btnBack)
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewRequestActionPerformed
        // TODO add your handling code here:
        if(patient.getPrefferedDoctorEnterprise()!=null)
        {
            CreateNewWorkRequestJPanel panel=new CreateNewWorkRequestJPanel(userProcessContainer,system,patient);
            userProcessContainer.add("CreateNewWorkRequest", panel);
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"patient is npt assigned to any enterprise");
            return;
        }
    }//GEN-LAST:event_btnCreateNewRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateNewRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable patientWorkRequestTable;
    // End of variables declaration//GEN-END:variables
}
