/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PatientRole;

import Business.EcoSystem;
import Business.Patient.Patient;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rekhajindal
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Patient patient;
    /**
     * Creates new form PatientWorkAreaJPanel
     */
    public PatientWorkAreaJPanel(JPanel upc,EcoSystem system,Patient patient) {
        initComponents();
        this.userProcessContainer=upc;
        this.system=system;
        this.patient=patient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageworkRequest = new javax.swing.JButton();
        btnManageLabWorkRequest = new javax.swing.JButton();
        btnManagePharmacyWorkRequest = new javax.swing.JButton();
        btnPharmaCompanyComm = new javax.swing.JButton();
        btnManagePatientrequest = new javax.swing.JButton();

        btnManageworkRequest.setText("Manage Doctor Work Request");
        btnManageworkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageworkRequestActionPerformed(evt);
            }
        });

        btnManageLabWorkRequest.setText("Manage Lab work Request");
        btnManageLabWorkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLabWorkRequestActionPerformed(evt);
            }
        });

        btnManagePharmacyWorkRequest.setText("Manage Pharmacy Work Request");
        btnManagePharmacyWorkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePharmacyWorkRequestActionPerformed(evt);
            }
        });

        btnPharmaCompanyComm.setText("View Pharma Company Communication");
        btnPharmaCompanyComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPharmaCompanyCommActionPerformed(evt);
            }
        });

        btnManagePatientrequest.setText("Manage Patient Work Request");
        btnManagePatientrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePatientrequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageworkRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageLabWorkRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManagePharmacyWorkRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPharmaCompanyComm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManagePatientrequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(228, 228, 228))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnManageworkRequest)
                .addGap(28, 28, 28)
                .addComponent(btnManageLabWorkRequest)
                .addGap(30, 30, 30)
                .addComponent(btnManagePharmacyWorkRequest)
                .addGap(28, 28, 28)
                .addComponent(btnPharmaCompanyComm)
                .addGap(29, 29, 29)
                .addComponent(btnManagePatientrequest)
                .addGap(103, 103, 103))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageworkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageworkRequestActionPerformed
        // TODO add your handling code here:
        ManageDoctorWorkRequestJPanel panel=new ManageDoctorWorkRequestJPanel(userProcessContainer,system,patient);
        userProcessContainer.add("ManageDoctorWorkRequest", panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageworkRequestActionPerformed

    private void btnManageLabWorkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLabWorkRequestActionPerformed
        // TODO add your handling code here:
        ManageLabWorkRequestJPanel panel= new ManageLabWorkRequestJPanel(userProcessContainer,patient);
        userProcessContainer.add("ManageLabWorkRequest", panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageLabWorkRequestActionPerformed

    private void btnManagePharmacyWorkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePharmacyWorkRequestActionPerformed
        // TODO add your handling code here:
      ManagePatientPharmacyWorkRequestJPanel panel=new ManagePatientPharmacyWorkRequestJPanel(userProcessContainer,patient);
      userProcessContainer.add("ManageLabWorkRequest", panel);
      CardLayout layout=(CardLayout)userProcessContainer.getLayout();
      layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePharmacyWorkRequestActionPerformed

    private void btnPharmaCompanyCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPharmaCompanyCommActionPerformed
        // TODO add your handling code here:
        WorkQueue wrkQueue=patient.getWorkQueue();
        ReceivedCommunicationWorkRequestJPanel panel=new ReceivedCommunicationWorkRequestJPanel(userProcessContainer,wrkQueue);
        userProcessContainer.add("ReceivedCommunicationJPanelPatient", panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPharmaCompanyCommActionPerformed

    private void btnManagePatientrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePatientrequestActionPerformed
        // TODO add your handling code here:
        ManagePatientWorkRequestJPanel panel=new ManagePatientWorkRequestJPanel(userProcessContainer,patient);
        userProcessContainer.add("ManagePatientRequestJPanelPatient", panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePatientrequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageLabWorkRequest;
    private javax.swing.JButton btnManagePatientrequest;
    private javax.swing.JButton btnManagePharmacyWorkRequest;
    private javax.swing.JButton btnManageworkRequest;
    private javax.swing.JButton btnPharmaCompanyComm;
    // End of variables declaration//GEN-END:variables
}
