/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PatientRole;

import Business.Doctor.Doctor;
import Business.Doctor.DoctorRatings;
import Business.Patient.Patient;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rekhajindal
 */
public class RateDoctorExperienceJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Patient patient;
    private Doctor doctor;
    /**
     * Creates new form RateDoctorExperienceJPanel
     */
    public RateDoctorExperienceJPanel(JPanel upc,Patient patient,Doctor doctor) {
        initComponents();
        this.userProcessContainer=upc;
        this.patient=patient;
        this.doctor=doctor;
        
        
    }

    public void calculateRating()
    {
        try
        {
        float rating1=0;
        float rating2=0;
        float rating3=0;
        float rating4=0;
        float rating5=0;
        float totalRating;
        if(oneradiobtn1.isSelected())
            rating1=1;
        if(oneradbtn2.isSelected())
            rating1=2;
        if(oneradbtn3.isSelected())
            rating1=3;
        if(oneradbtn4.isSelected())
            rating1=4;
        if(oneradbtn5.isSelected())
            rating1=5;
        if(tworadbtn1.isSelected())
            rating2=1;
        if(tworadbtn2.isSelected())
            rating2=2;
        if(tworadbtn3.isSelected())
            rating2=3;
        if(tworadbtn4.isSelected())
            rating2=4;
        if(tworadbtn5.isSelected())
            rating2=5;
        if(threeradbtn1.isSelected())
            rating3=1;
        if(threeradbtn2.isSelected())
            rating3=2;
        if(threeradbtn3.isSelected())
            rating3=3;
        if(threeradbtn4.isSelected())
            rating3=4;
        if(threeradbtn5.isSelected())
            rating3=5;
        if(fourradbtn1.isSelected())
            rating4=1;
        if(fourradbtn2.isSelected())
            rating4=2;
        if(fourradbtn3.isSelected())
            rating4=3;
        if(fourradbtn4.isSelected())
            rating4=4;
        if(fourradbtn5.isSelected())
            rating4=5;
        if(fiveradbtn1.isSelected())
            rating5=1;
         if(fiveradbtn2.isSelected())
            rating5=2;
          if(fiveradbtn3.isSelected())
            rating5=3;
         if(fiveradbtn4.isSelected())
            rating5=4;
         if(fiveradbtn5.isSelected())
            rating5=5;
         
         if (buttonGroup1.isSelected(null) || buttonGroup2.isSelected(null) || buttonGroup3.isSelected(null)
                 || buttonGroup4.isSelected(null) || buttonGroup5.isSelected(null))
         {
             JOptionPane.showMessageDialog(null, "please give rating for all options");
             return;
         }
        float sumofrating=rating1+rating2+rating3+rating4+rating5;
        totalRating=(sumofrating/25)*5;
        String message=txtArea.getText();
        if(message.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "please give comments too");
             return;
        }
        DoctorRatings rating=new DoctorRatings();
        rating.setRating(totalRating);
        rating.setReview(message);
        rating.setPatient(patient);
        doctor.getRatingList().add(rating);
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null,"please enter proper values");
            return;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        oneradiobtn1 = new javax.swing.JRadioButton();
        oneradbtn2 = new javax.swing.JRadioButton();
        oneradbtn3 = new javax.swing.JRadioButton();
        oneradbtn4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tworadbtn3 = new javax.swing.JRadioButton();
        tworadbtn4 = new javax.swing.JRadioButton();
        tworadbtn1 = new javax.swing.JRadioButton();
        tworadbtn2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        threeradbtn3 = new javax.swing.JRadioButton();
        threeradbtn2 = new javax.swing.JRadioButton();
        threeradbtn1 = new javax.swing.JRadioButton();
        threeradbtn4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        fourradbtn1 = new javax.swing.JRadioButton();
        fourradbtn4 = new javax.swing.JRadioButton();
        fourradbtn2 = new javax.swing.JRadioButton();
        fourradbtn3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        fiveradbtn4 = new javax.swing.JRadioButton();
        fiveradbtn1 = new javax.swing.JRadioButton();
        fiveradbtn2 = new javax.swing.JRadioButton();
        fiveradbtn3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        tworadbtn5 = new javax.swing.JRadioButton();
        fourradbtn5 = new javax.swing.JRadioButton();
        threeradbtn5 = new javax.swing.JRadioButton();
        oneradbtn5 = new javax.swing.JRadioButton();
        fiveradbtn5 = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("1. I receive the exactly care I want and need ?");

        buttonGroup1.add(oneradiobtn1);
        oneradiobtn1.setText("1");

        buttonGroup1.add(oneradbtn2);
        oneradbtn2.setText("2");

        buttonGroup1.add(oneradbtn3);
        oneradbtn3.setText("3");

        buttonGroup1.add(oneradbtn4);
        oneradbtn4.setText("4");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("2. My care is Perfect ?");

        buttonGroup2.add(tworadbtn3);
        tworadbtn3.setText("3");

        buttonGroup2.add(tworadbtn4);
        tworadbtn4.setText("4");

        buttonGroup2.add(tworadbtn1);
        tworadbtn1.setText("1");

        buttonGroup2.add(tworadbtn2);
        tworadbtn2.setText("2");
        tworadbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tworadbtn2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("3. It is very easy to get care  when I need it ? ");

        buttonGroup3.add(threeradbtn3);
        threeradbtn3.setText("3");

        buttonGroup3.add(threeradbtn2);
        threeradbtn2.setText("2");
        threeradbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeradbtn2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(threeradbtn1);
        threeradbtn1.setText("1");

        buttonGroup3.add(threeradbtn4);
        threeradbtn4.setText("4");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("4.My doctor is aware of my emotional issues ?");

        buttonGroup4.add(fourradbtn1);
        fourradbtn1.setText("1");

        buttonGroup4.add(fourradbtn4);
        fourradbtn4.setText("4");

        buttonGroup4.add(fourradbtn2);
        fourradbtn2.setText("2");
        fourradbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourradbtn2ActionPerformed(evt);
            }
        });

        buttonGroup4.add(fourradbtn3);
        fourradbtn3.setText("3");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("5. My doctor's office is well organized,efficient and does not waste my time ? ");

        buttonGroup5.add(fiveradbtn4);
        fiveradbtn4.setText("4");

        buttonGroup5.add(fiveradbtn1);
        fiveradbtn1.setText("1");

        buttonGroup5.add(fiveradbtn2);
        fiveradbtn2.setText("2");
        fiveradbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveradbtn2ActionPerformed(evt);
            }
        });

        buttonGroup5.add(fiveradbtn3);
        fiveradbtn3.setText("3");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Review And Comments");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        buttonGroup2.add(tworadbtn5);
        tworadbtn5.setText("5");

        buttonGroup4.add(fourradbtn5);
        fourradbtn5.setText("5");

        buttonGroup3.add(threeradbtn5);
        threeradbtn5.setText("5");

        buttonGroup1.add(oneradbtn5);
        oneradbtn5.setText("5");

        buttonGroup5.add(fiveradbtn5);
        fiveradbtn5.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(threeradbtn1)
                        .addGap(10, 10, 10)
                        .addComponent(threeradbtn2)
                        .addGap(10, 10, 10)
                        .addComponent(threeradbtn3)
                        .addGap(18, 18, 18)
                        .addComponent(threeradbtn4)
                        .addGap(18, 18, 18)
                        .addComponent(threeradbtn5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(153, 153, 153)
                                .addComponent(btnSubmit))
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tworadbtn1)
                                        .addGap(10, 10, 10)
                                        .addComponent(tworadbtn2)
                                        .addGap(10, 10, 10)
                                        .addComponent(tworadbtn3)
                                        .addGap(18, 18, 18)
                                        .addComponent(tworadbtn4)
                                        .addGap(18, 18, 18)
                                        .addComponent(tworadbtn5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(oneradiobtn1)
                                        .addGap(10, 10, 10)
                                        .addComponent(oneradbtn2)
                                        .addGap(10, 10, 10)
                                        .addComponent(oneradbtn3)
                                        .addGap(18, 18, 18)
                                        .addComponent(oneradbtn4)
                                        .addGap(18, 18, 18)
                                        .addComponent(oneradbtn5))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fourradbtn1)
                                .addGap(10, 10, 10)
                                .addComponent(fourradbtn2)
                                .addGap(10, 10, 10)
                                .addComponent(fourradbtn3)
                                .addGap(18, 18, 18)
                                .addComponent(fourradbtn4)
                                .addGap(18, 18, 18)
                                .addComponent(fourradbtn5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(fiveradbtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fiveradbtn2)
                        .addGap(18, 18, 18)
                        .addComponent(fiveradbtn3)
                        .addGap(18, 18, 18)
                        .addComponent(fiveradbtn4)
                        .addGap(18, 18, 18)
                        .addComponent(fiveradbtn5)))
                .addGap(229, 229, 229))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oneradiobtn1)
                    .addComponent(oneradbtn2)
                    .addComponent(oneradbtn3)
                    .addComponent(oneradbtn4)
                    .addComponent(oneradbtn5))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tworadbtn1)
                    .addComponent(tworadbtn2)
                    .addComponent(tworadbtn3)
                    .addComponent(tworadbtn4)
                    .addComponent(tworadbtn5))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threeradbtn1)
                    .addComponent(threeradbtn2)
                    .addComponent(threeradbtn3)
                    .addComponent(threeradbtn4)
                    .addComponent(threeradbtn5))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourradbtn1)
                    .addComponent(fourradbtn2)
                    .addComponent(fourradbtn3)
                    .addComponent(fourradbtn4)
                    .addComponent(fourradbtn5))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiveradbtn1)
                    .addComponent(fiveradbtn2)
                    .addComponent(fiveradbtn3)
                    .addComponent(fiveradbtn4)
                    .addComponent(fiveradbtn5))
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnBack))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tworadbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tworadbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tworadbtn2ActionPerformed

    private void threeradbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeradbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threeradbtn2ActionPerformed

    private void fourradbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourradbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fourradbtn2ActionPerformed

    private void fiveradbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveradbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiveradbtn2ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        calculateRating();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JRadioButton fiveradbtn1;
    private javax.swing.JRadioButton fiveradbtn2;
    private javax.swing.JRadioButton fiveradbtn3;
    private javax.swing.JRadioButton fiveradbtn4;
    private javax.swing.JRadioButton fiveradbtn5;
    private javax.swing.JRadioButton fourradbtn1;
    private javax.swing.JRadioButton fourradbtn2;
    private javax.swing.JRadioButton fourradbtn3;
    private javax.swing.JRadioButton fourradbtn4;
    private javax.swing.JRadioButton fourradbtn5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton oneradbtn2;
    private javax.swing.JRadioButton oneradbtn3;
    private javax.swing.JRadioButton oneradbtn4;
    private javax.swing.JRadioButton oneradbtn5;
    private javax.swing.JRadioButton oneradiobtn1;
    private javax.swing.JRadioButton threeradbtn1;
    private javax.swing.JRadioButton threeradbtn2;
    private javax.swing.JRadioButton threeradbtn3;
    private javax.swing.JRadioButton threeradbtn4;
    private javax.swing.JRadioButton threeradbtn5;
    private javax.swing.JRadioButton tworadbtn1;
    private javax.swing.JRadioButton tworadbtn2;
    private javax.swing.JRadioButton tworadbtn3;
    private javax.swing.JRadioButton tworadbtn4;
    private javax.swing.JRadioButton tworadbtn5;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
