/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PatientRole;

import Business.Doctor.Doctor;
import Business.Doctor.DoctorRatings;
import Business.Patient.Patient;
import Business.WorkQueue.PatientToPatientWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rekhajindal
 */
public class ViewDoctorRatingAndReviewsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Doctor doctor;
    private Patient patient;
    /**
     * Creates new form ViewDoctorRatingAndReviewsJPanel
     */
    public ViewDoctorRatingAndReviewsJPanel(JPanel upc,Doctor doctor,Patient patient) {
        initComponents();
        this.userProcessContainer=upc;
        this.doctor=doctor;
        this.patient=patient;
        populateRatingTable();
        msgPanel.setVisible(false);
        enquireMsgPanel.setVisible(false);
    }

    
    public void populateRatingTable()
    {
        DefaultTableModel model=(DefaultTableModel)RatingDetailsJtable.getModel();
        model.setRowCount(0);
        for(DoctorRatings rating:doctor.getRatingList())
        {
            Object[]row=new Object[3];
            row[0]=rating;
            row[1]=doctor.getFirstName();
            row[2]=rating.getPatient().getFirstName();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RatingDetailsJtable = new javax.swing.JTable();
        btnPatientReviews = new javax.swing.JButton();
        msgPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareamsg = new javax.swing.JTextArea();
        btnEnquirePatients = new javax.swing.JButton();
        enquireMsgPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        enquiremsgtxtArea = new javax.swing.JTextArea();
        btnSendmsgPatient = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        jLabel1.setText("Details of Rating and Reviews");

        RatingDetailsJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Rating(out of 5)", "Doctor Name", "By Patient"
            }
        ));
        jScrollPane1.setViewportView(RatingDetailsJtable);

        btnPatientReviews.setText("Get Patient Reviews");
        btnPatientReviews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientReviewsActionPerformed(evt);
            }
        });

        txtareamsg.setColumns(20);
        txtareamsg.setRows(5);
        jScrollPane2.setViewportView(txtareamsg);

        javax.swing.GroupLayout msgPanelLayout = new javax.swing.GroupLayout(msgPanel);
        msgPanel.setLayout(msgPanelLayout);
        msgPanelLayout.setHorizontalGroup(
            msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        msgPanelLayout.setVerticalGroup(
            msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnEnquirePatients.setText("Enquire with Patients");
        btnEnquirePatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnquirePatientsActionPerformed(evt);
            }
        });

        enquiremsgtxtArea.setColumns(20);
        enquiremsgtxtArea.setRows(5);
        jScrollPane3.setViewportView(enquiremsgtxtArea);

        javax.swing.GroupLayout enquireMsgPanelLayout = new javax.swing.GroupLayout(enquireMsgPanel);
        enquireMsgPanel.setLayout(enquireMsgPanelLayout);
        enquireMsgPanelLayout.setHorizontalGroup(
            enquireMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enquireMsgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        enquireMsgPanelLayout.setVerticalGroup(
            enquireMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enquireMsgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        btnSendmsgPatient.setText("Send Message to Patient");
        btnSendmsgPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendmsgPatientActionPerformed(evt);
            }
        });

        btnback.setText("<< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnback)
                            .addComponent(msgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnPatientReviews)
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enquireMsgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnquirePatients, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(btnSendmsgPatient)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPatientReviews)
                    .addComponent(btnEnquirePatients))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enquireMsgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSendmsgPatient)
                .addGap(18, 18, 18)
                .addComponent(btnback)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientReviewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientReviewsActionPerformed
        // TODO add your handling code here:
        int selectedRow=RatingDetailsJtable.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "please select a row");
            return;
        }
        msgPanel.setVisible(true);
//        enquireMsgPanel.setVisible(false);
        DoctorRatings rating=(DoctorRatings)RatingDetailsJtable.getValueAt(selectedRow, 0);
        txtareamsg.setText(rating.getReview());
    }//GEN-LAST:event_btnPatientReviewsActionPerformed

    private void btnEnquirePatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnquirePatientsActionPerformed
        // TODO add your handling code here:
        
        int selectedRow=RatingDetailsJtable.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "please select a row");
            return;
        }
//        msgPanel.setVisible(false);
        enquireMsgPanel.setVisible(true);
        
        
    }//GEN-LAST:event_btnEnquirePatientsActionPerformed

    private void btnSendmsgPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendmsgPatientActionPerformed
        // TODO add your handling code here:
        int selectedRow=RatingDetailsJtable.getSelectedRow();
        String message=enquiremsgtxtArea.getText();
        if(message.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "please enter the message");
            return;
        }
        DoctorRatings rating=(DoctorRatings)RatingDetailsJtable.getValueAt(selectedRow, 0);
        PatientToPatientWorkRequest request=new PatientToPatientWorkRequest();
        request.setMessage(message);
        request.setSender(patient);
        request.setReceiver(rating.getPatient());
        request.setDoctorName(doctor.getFirstName());
        patient.getWorkQueue().getWorkRequestList().add(request);
        rating.getPatient().getWorkQueue().getWorkRequestList().add(request);
    }//GEN-LAST:event_btnSendmsgPatientActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RatingDetailsJtable;
    private javax.swing.JButton btnEnquirePatients;
    private javax.swing.JButton btnPatientReviews;
    private javax.swing.JButton btnSendmsgPatient;
    private javax.swing.JButton btnback;
    private javax.swing.JPanel enquireMsgPanel;
    private javax.swing.JTextArea enquiremsgtxtArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel msgPanel;
    private javax.swing.JTextArea txtareamsg;
    // End of variables declaration//GEN-END:variables
}
