/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PharmacyRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyCompanyEnterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.Network;
import Business.Network.NetworkCity;
import Business.Network.NetworkState;
import Business.PharmaceuticalCompany.Drug;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rekhajindal
 */
public class AddDrugJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private Enterprise enterprise;
    private PharmacyCompanyEnterprise pcEnterprise;
    /**
     * Creates new form AddDrugJPanel
     */
    public AddDrugJPanel(JPanel upc,EcoSystem system,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=upc;
        this.system=system;
        this.enterprise=enterprise;
        populateCompanyDetailsTable();
    }

    public void populateCompanyDetailsTable()
    {
        DefaultTableModel model=(DefaultTableModel)CompanyDetailsJTable.getModel();
        model.setRowCount(0);
        for(Network country:system.getNetworkList())
        {
            for(NetworkState state:country.getNetworkStateList())
            {
                for(NetworkCity city:state.getNetworkCityList())
                {
                    for(Enterprise enterprise:city.getEnterpriseDirectory().getEnterpriseList())
                    {
                        if(enterprise instanceof PharmacyCompanyEnterprise)
                        {
                            Object[]row=new Object[2];
                            row[0]=enterprise;
                            row[1]=enterprise.getOrganizationID();
                            model.addRow(row);
                        }
                    }
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        CompanyDetailsJTable = new javax.swing.JTable();
        btnSelectCompany = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DrugDetailsJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnAddDrug = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        CompanyDetailsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Company Name", "Company ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(CompanyDetailsJTable);

        btnSelectCompany.setText("Select Company");
        btnSelectCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCompanyActionPerformed(evt);
            }
        });

        jLabel1.setText("Company Details");

        DrugDetailsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug ID", "Drug Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(DrugDetailsJTable);

        jLabel2.setText("Drug Details");

        btnAddDrug.setText("Add Drug");
        btnAddDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrugActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnBack)
                .addContainerGap(629, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jLabel1))
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(206, 206, 206)
                            .addComponent(btnSelectCompany))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(226, 226, 226)
                            .addComponent(btnAddDrug)))
                    .addContainerGap(121, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(557, 557, 557)
                .addComponent(btnBack)
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(jLabel1)
                    .addGap(31, 31, 31)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)
                    .addComponent(btnSelectCompany)
                    .addGap(54, 54, 54)
                    .addComponent(jLabel2)
                    .addGap(45, 45, 45)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36)
                    .addComponent(btnAddDrug)
                    .addContainerGap(75, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCompanyActionPerformed
        // TODO add your handling code here:
        int selectedRow=CompanyDetailsJTable.getSelectedRow();
        if(selectedRow <0)
        {
            JOptionPane.showMessageDialog(null, "Please select atleast one row");
            return;
        }
        
        Enterprise enterprise=(Enterprise)CompanyDetailsJTable.getValueAt(selectedRow,0);
        pcEnterprise=(PharmacyCompanyEnterprise)enterprise;
        populateDrugDetails(enterprise);
        
        
        
    }//GEN-LAST:event_btnSelectCompanyActionPerformed

    private void btnAddDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrugActionPerformed
        // TODO add your handling code here:
        int selectedRow=DrugDetailsJTable.getSelectedRow();
        if(selectedRow <0)
        {
            JOptionPane.showMessageDialog(null, "Please select atleast one row");
            return;
        }
        Drug drug=(Drug)DrugDetailsJTable.getValueAt(selectedRow, 0);
        PharmacyEnterprise phEnterprise=(PharmacyEnterprise)enterprise;
        for(Drug listDrug:phEnterprise.getPharmacyDrugList())
        {
            if(drug.getDrugID()==listDrug.getDrugID())
            {
                JOptionPane.showMessageDialog(null, "This drug is already presenet in list");
                return;
            }
        }
        phEnterprise.getPharmacyDrugList().add(drug);
        for(PharmacyEnterprise enterprise: pcEnterprise.getPharmacyList())
        {
            if(enterprise.getOrganizationID()==phEnterprise.getOrganizationID())
            {
                
                return;
            }
         
        }
        pcEnterprise.getPharmacyList().add(phEnterprise);
        
    }//GEN-LAST:event_btnAddDrugActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    public void populateDrugDetails(Enterprise enterprise)
    {
        DefaultTableModel model=(DefaultTableModel)DrugDetailsJTable.getModel();
        model.setRowCount(0);
        
        for(Drug drug:pcEnterprise.getDrugList())
        {
            if(drug.getDrugStatus().equals("Approved"))
            {
            Object[]row=new Object[3];
            row[0]=drug;
            row[1]=drug.getDrugName();
            row[2]=drug.getPrice();
            model.addRow(row);
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CompanyDetailsJTable;
    private javax.swing.JTable DrugDetailsJTable;
    private javax.swing.JButton btnAddDrug;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSelectCompany;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
