/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PharmacyRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.PharmaceuticalCompany.Drug;
import Business.WorkQueue.DrugCallBackRequestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rekhajindal
 */
public class ViewDrugCallBackJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    /**
     * Creates new form ViewDrugCallBackJPanel
     */
    public ViewDrugCallBackJPanel(JPanel upc,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=upc;
        this.enterprise=enterprise;
        populateDrugCallBackTable();
    }

    private void populateDrugCallBackTable()
    {
        DefaultTableModel model=(DefaultTableModel)CallBackRequestTable.getModel();
        model.setRowCount(0);
        for(WorkRequest request:enterprise.getWorkQueue().getWorkRequestList())
        {
            if(request instanceof DrugCallBackRequestWorkRequest)
            {
                DrugCallBackRequestWorkRequest drugCallRequest=(DrugCallBackRequestWorkRequest)request;
                Object[]row=new Object[4];
                row[0]=drugCallRequest;
                row[1]=drugCallRequest.getDrug();
                row[2]=drugCallRequest.getDrug().getDrugName();
                row[3]=drugCallRequest.getSenderEnterprise().getName();
                model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CallBackRequestTable = new javax.swing.JTable();
        btnProcessRequest = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        jLabel1.setText("List of call back request");

        CallBackRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Drug ID", "Drug Name", "Enterprise Name"
            }
        ));
        jScrollPane1.setViewportView(CallBackRequestTable);

        btnProcessRequest.setText("Process Request");
        btnProcessRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessRequestActionPerformed(evt);
            }
        });

        btnback.setText("<< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btnProcessRequest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnback)))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnProcessRequest)
                .addGap(117, 117, 117)
                .addComponent(btnback)
                .addGap(107, 107, 107))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow=CallBackRequestTable.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"please select a row");
            return;
        }
        Drug drug=(Drug)CallBackRequestTable.getValueAt(selectedRow,1);
        PharmacyEnterprise phEnterprise=(PharmacyEnterprise)enterprise;
        
        boolean result=false;
        for(Drug findDrug:phEnterprise.getPharmacyDrugList())
        {
            
            if(findDrug.getDrugID()==drug.getDrugID())
            {
                phEnterprise.getPharmacyDrugList().remove(drug);
                result=true;
                break;
            }
            
        }
        if(result==false)
        {
            JOptionPane.showMessageDialog(null, "Sorry u are not allowed to process");
            return;
        }
        
        
    }//GEN-LAST:event_btnProcessRequestActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CallBackRequestTable;
    private javax.swing.JButton btnProcessRequest;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
