/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SystemAdminWorkAreaJPanel;

import Business.EcoSystem;
import Business.Network.Network;
import Business.Network.NetworkCity;
import Business.Network.NetworkState;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rekhajindal
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    /**
     * Creates new form ManageNetworkJPanel
     */
    public ManageNetworkJPanel(JPanel upc, EcoSystem system) {
        initComponents();
        this.userProcessContainer=upc;
        this.system=system;
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btnback = new javax.swing.JButton();
        BtnManageState = new javax.swing.JButton();
        BtnManageCity = new javax.swing.JButton();
        btnManageCountry = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Btnback.setText("<< Back");
        Btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbackActionPerformed(evt);
            }
        });

        BtnManageState.setText("Manage States");
        BtnManageState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageStateActionPerformed(evt);
            }
        });

        BtnManageCity.setText("Manage City");
        BtnManageCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageCityActionPerformed(evt);
            }
        });

        btnManageCountry.setText("Manage Country");
        btnManageCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCountryActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Manage Networks for Internet Health Care");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnManageCity, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnManageState, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(Btnback))))
                .addGap(280, 280, 280))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(btnManageCountry)
                .addGap(27, 27, 27)
                .addComponent(BtnManageState)
                .addGap(26, 26, 26)
                .addComponent(BtnManageCity)
                .addGap(153, 153, 153)
                .addComponent(Btnback)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BtnbackActionPerformed

    private void BtnManageStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageStateActionPerformed
        // TODO add your handling code here:
        for(Network network:system.getNetworkList())
        {
            if(network !=null)
            {
                ManageStateJPanel panel= new ManageStateJPanel(userProcessContainer,system);
                userProcessContainer.add("ManageStatePanel", panel);
                CardLayout layout=(CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                return;
            }
        }
        JOptionPane.showMessageDialog(null,"please add a country");
        
    }//GEN-LAST:event_BtnManageStateActionPerformed

    private void BtnManageCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageCityActionPerformed
        // TODO add your handling code here:
        for(Network network:system.getNetworkList())
        {
            for(NetworkState state:network.getNetworkStateList())
            {
                if(state !=null)
                {
                     ManageCityJPanel panel=new ManageCityJPanel(userProcessContainer,system);
                     userProcessContainer.add("ManageCityPanel", panel);
                     CardLayout layout=(CardLayout)userProcessContainer.getLayout();
                     layout.next(userProcessContainer);
                     return;
                    
                }
            }
        }
       JOptionPane.showMessageDialog(null,"please add a state");
    }//GEN-LAST:event_BtnManageCityActionPerformed

    private void btnManageCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCountryActionPerformed
        // TODO add your handling code here:
        ManageCountryJPanel panel= new ManageCountryJPanel(userProcessContainer,system);
        userProcessContainer.add("ManageCountryPanel", panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageCountryActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnManageCity;
    private javax.swing.JButton BtnManageState;
    private javax.swing.JButton Btnback;
    private javax.swing.JButton btnManageCountry;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
