/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SystemAdminWorkAreaJPanel;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Network.Network;
import Business.Network.NetworkCity;
import Business.Network.NetworkState;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rekhajindal
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseJPanel(JPanel upc, EcoSystem system) {
        initComponents();
        this.userProcessContainer=upc;
        this.system=system;
        populateNetworkCountryCombo();
        populateEnterprisetype();
        populateEnterpriseTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EnterpriseJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Combonetworkstate = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        comboEnterprisetype = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtEnterprisename = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboNetworkCity = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboCountry = new javax.swing.JComboBox();
        btnDelete = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();

        EnterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "EnterpriseName", "Enterprise Type", "Network Country", "NetworkState", "NetworkCity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(EnterpriseJTable);

        jLabel1.setText("Select State");

        Combonetworkstate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Combonetworkstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombonetworkstateActionPerformed(evt);
            }
        });

        jLabel2.setText("Type of Enterprise");

        comboEnterprisetype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Enterprise Name");

        txtEnterprisename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterprisenameActionPerformed(evt);
            }
        });

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel4.setText("Select City");

        comboNetworkCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboNetworkCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNetworkCityActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Enterprise Details");

        jLabel6.setText("Select Country");

        comboCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCountryActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnBack)
                                .addGap(161, 161, 161)
                                .addComponent(btnsubmit))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Combonetworkstate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEnterprisename)
                            .addComponent(comboEnterprisetype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboNetworkCity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnrefresh))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Combonetworkstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboNetworkCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboEnterprisetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEnterprisename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnsubmit))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnterprisenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterprisenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterprisenameActionPerformed

    private void CombonetworkstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombonetworkstateActionPerformed
        // TODO add your handling code here:
        NetworkState networkState=(NetworkState)Combonetworkstate.getSelectedItem();
        if(networkState != null)
        {
        populateNetworkCityCombo(networkState);
        }
        
    }//GEN-LAST:event_CombonetworkstateActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        
        if(comboCountry.getItemCount()==0)
        {
            JOptionPane.showMessageDialog(null,"please add country");
            return;
        }
        
        if(Combonetworkstate.getItemCount()==0)
        {
            JOptionPane.showMessageDialog(null,"please add state");
            return;
        }
        
        NetworkCity city=(NetworkCity)comboNetworkCity.getSelectedItem();
        Enterprise.EnterpriseType type=(Enterprise.EnterpriseType)comboEnterprisetype.getSelectedItem();
        
         if (city == null || type == null){
            JOptionPane.showMessageDialog(null, "please select proper city and enterprise");
            return;
        }
        String enterpriseName=txtEnterprisename.getText();
        if(enterpriseName.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"please add enterprisename");
            return;
        }
        for(Enterprise enterprise:city.getEnterpriseDirectory().getEnterpriseList())
        {
            if(enterprise.getName().equals(enterpriseName))
            {
                JOptionPane.showMessageDialog(null,"This enterprise is already present");
                return;
            }
        }
       Enterprise enterprise= city.getEnterpriseDirectory().createAndAddEnterprise(enterpriseName, type);
       populateEnterpriseTable();
       txtEnterprisename.setText("");
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCountryActionPerformed
        // TODO add your handling code here:
        Network network=(Network)comboCountry.getSelectedItem();
        if(network != null)
        {
            populateNetworkStateCombo(network);
        }
    }//GEN-LAST:event_comboCountryActionPerformed

    private void comboNetworkCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNetworkCityActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboNetworkCityActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = EnterpriseJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select atleast one row");
            return;
        }
        NetworkCity city=(NetworkCity)EnterpriseJTable.getValueAt(selectedRow,4);
        Enterprise enterprise=(Enterprise)EnterpriseJTable.getValueAt(selectedRow, 0);
        city.getEnterpriseDirectory().getEnterpriseList().remove(enterprise);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        populateEnterpriseTable();
    }//GEN-LAST:event_btnrefreshActionPerformed

    public void populateNetworkCityCombo(NetworkState networkState)
    {
        comboNetworkCity.removeAllItems();
      for(NetworkCity city:networkState.getNetworkCityList())
       {
           comboNetworkCity.addItem(city);
       }
    }

    public void populateNetworkCountryCombo()
    {
        comboCountry.removeAllItems();
        for(Network network:system.getNetworkList())
        {
            comboCountry.addItem(network);
        }
    }
    public void populateEnterprisetype()
    {
        comboEnterprisetype.removeAllItems();
        for(Enterprise.EnterpriseType type:Enterprise.EnterpriseType.values())
        {
            comboEnterprisetype.addItem(type);
        }
        
    }
    
    public void populateNetworkStateCombo(Network network )
    {
        Combonetworkstate.removeAllItems();
        for(NetworkState state: network.getNetworkStateList())
        {
            Combonetworkstate.addItem(state);
        }
    }
    
    public void populateEnterpriseTable()
    {
        DefaultTableModel model=(DefaultTableModel)EnterpriseJTable.getModel();
        model.setRowCount(0);
        
        for(Network network:system.getNetworkList())
        {
            for(NetworkState state:network.getNetworkStateList())
            {
            for(NetworkCity city:state.getNetworkCityList())
            {
                for(Enterprise enterprise: city.getEnterpriseDirectory().getEnterpriseList())
                {
                    Object[]row=new Object[5];
                    row[0]=enterprise;
                    row[1]=enterprise.getEnterpriseType().getValue();
                    row[2]=network;
                    row[3]=state;
                    row[4]=city;
                    model.addRow(row);
                }
            }
            
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combonetworkstate;
    private javax.swing.JTable EnterpriseJTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox comboCountry;
    private javax.swing.JComboBox comboEnterprisetype;
    private javax.swing.JComboBox comboNetworkCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEnterprisename;
    // End of variables declaration//GEN-END:variables
}
