/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.Enterprise.ClinicEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PharmacyCompanyEnterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rekhajindal
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(JPanel upc, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = upc;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        populateOrganizationCombo();
        populateOrganizationTable();
    }

    public void populateOrganizationCombo() {
        comboOrganizationType.removeAllItems();

        if (enterprise instanceof HospitalEnterprise) 
        {
            for (Type type : Organization.Type.values()) {
                if (type.getValue().equals(Type.Doctor.getValue()) || type.getValue().equals(Type.LabAssistant.getValue()) || type.getValue().equals(Type.Patient.getValue()) )
                {
                    comboOrganizationType.addItem(type);
                }
            }
        }
         else if (enterprise instanceof ClinicEnterprise) 
          {
            for (Type type : Organization.Type.values()) 
            {
                if (type.getValue().equals(Type.Doctor.getValue()) || type.getValue().equals(Type.LabAssistant.getValue())|| type.getValue().equals(Type.Patient.getValue()) )
                {
                    comboOrganizationType.addItem(type);
                }
            }
         }
        
        else if (enterprise instanceof PharmacyEnterprise) 
          {
            for (Type type : Organization.Type.values()) 
            {
                if (type.getValue().equals(Type.PharmacyStores.getValue())) 
                {
                    comboOrganizationType.addItem(type);
                }
            }
         }
        
        else if (enterprise instanceof PharmacyCompanyEnterprise) 
          {
            for (Type type : Organization.Type.values()) 
            {
                if (type.getValue().equals(Type.DrugManagement.getValue()))
                {
                    comboOrganizationType.addItem(type);
                }
            }
         }
        }

    

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OrganizationJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        comboOrganizationType = new javax.swing.JComboBox();
        btnsubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        OrganizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Type ", "Enterprise Type", "Enterprise Name"
            }
        ));
        jScrollPane1.setViewportView(OrganizationJTable);

        jLabel1.setText("Organization Type");

        comboOrganizationType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboOrganizationType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOrganizationTypeActionPerformed(evt);
            }
        });

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(btnsubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(comboOrganizationType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboOrganizationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnsubmit)
                .addGap(41, 41, 41)
                .addComponent(btnBack)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        Type type=(Type)comboOrganizationType.getSelectedItem();
        for(Organization org:enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(type.getValue().equalsIgnoreCase(org.getName()))
            {
                JOptionPane.showMessageDialog(null, "This organization already exists.");
                return;
            }
        }
        enterprise.getOrganizationDirectory().createOrganization(type);
        populateOrganizationTable();
        
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboOrganizationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOrganizationTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOrganizationTypeActionPerformed

    public void populateOrganizationTable()
    {
        DefaultTableModel model=(DefaultTableModel)OrganizationJTable.getModel();
        model.setRowCount(0);
        for(Organization org:enterprise.getOrganizationDirectory().getOrganizationList())
        {
            Object[]row=new Object[4];
            row[0]=org.getOrganizationID();
            row[1]=org;
            row[2]=enterprise.getEnterpriseType();
            row[3]=enterprise.getName();
            model.addRow(row);
        }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrganizationJTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox comboOrganizationType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
