/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.Doctor.Doctor;
import Business.Encounter.Encounter;
import Business.Enterprise.ClinicEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.Network;
import Business.Network.NetworkCity;
import Business.Network.NetworkState;
import Business.Organization.LabAssistantOrganization;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.PharmaceuticalCompany.Drug;
import Business.WorkQueue.EncounterLabWorkRequest;
import Business.WorkQueue.PharmacyWorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rekhajindal
 */
public class AddEncounterJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Doctor doctor;
    private Patient patient;
    private Enterprise enterprise;
    private ArrayList<Network>networkList;

    /**
     * Creates new form AddEncounterJPanel
     */
    public AddEncounterJPanel(JPanel upc, Doctor doctor, Patient patient,Enterprise enterprise,ArrayList<Network>networkList) {
        initComponents();
        this.userProcessContainer = upc;
        this.doctor = doctor;
        this.patient = patient;
        this.enterprise=enterprise;
        this.networkList=networkList;
        populateCountryCombo();
        hideControls();
        
    }

    public void hideControls() {
        txtMessage.setVisible(false);
        labelMessage.setVisible(false);
        if(patient.getPreffredDoctor()==doctor)
        {
            //btnClosecase.setVisible(false);
        }
    }

    public void populateCountryCombo()
    {
        comboCountry.removeAllItems();
        for(Network country:networkList)
        {
            comboCountry.addItem(country);
        }
        
    }
    
    public void populateStateCombo(Network country)
    {
        comboState.removeAllItems();
        for(NetworkState state: country.getNetworkStateList())
        {
            comboState.addItem(state);
        }
    }
    
    public void populateCityCombo(NetworkState state)
    {
        comboCity.removeAllItems();
        for(NetworkCity city:state.getNetworkCityList())
        {
            comboCity.addItem(city);
        }
    }
    
    public void populatePharmacyCombo(NetworkCity city)
    {
        comboPharmacy.removeAllItems();
        for(Enterprise enterprise:city.getEnterpriseDirectory().getEnterpriseList())
        {
            if(enterprise instanceof PharmacyEnterprise)
            {
                comboPharmacy.addItem(enterprise);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBloodPressure = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRespiratory = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHeartRate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMedication = new javax.swing.JTextField();
        btnradioRequired = new javax.swing.JRadioButton();
        btnRadioNotrequired = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        labelMessage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtPrescription = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboCountry = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        comboState = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        comboCity = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        comboPharmacy = new javax.swing.JComboBox();
        labelPharmacy = new javax.swing.JLabel();
        txtPharmacyMessage = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        combodrug = new javax.swing.JComboBox();
        lblDrugName = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Add Vital Signs");

        jLabel2.setText("Weight");

        jLabel3.setText("Height");

        jLabel4.setText("Blood Pressure");

        txtBloodPressure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPressureActionPerformed(evt);
            }
        });

        jLabel5.setText("Respiratory Details");

        jLabel6.setText("Heart Rate");

        jLabel7.setText("Temperature");

        jLabel8.setText("Medication");

        buttonGroup1.add(btnradioRequired);
        btnradioRequired.setText(" Required");
        btnradioRequired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnradioRequiredActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnRadioNotrequired);
        btnRadioNotrequired.setText("Not Required");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Lab Test");

        labelMessage.setText("Message for Lab Assistant");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel11.setText("prescription");

        jLabel10.setText("Select Country");

        comboCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCountryActionPerformed(evt);
            }
        });

        jLabel12.setText("Select State");

        comboState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStateActionPerformed(evt);
            }
        });

        jLabel13.setText("Select City");

        comboCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCityActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Pharmacy Details");

        jLabel15.setText("List of Pharmacies");

        comboPharmacy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPharmacyActionPerformed(evt);
            }
        });

        labelPharmacy.setText("Message for Pharmacy");

        jLabel16.setText("Select Drug ");

        combodrug.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combodrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combodrugActionPerformed(evt);
            }
        });

        lblDrugName.setText("jLabel17");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelMessage)
                                .addGap(18, 18, 18)
                                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(btnradioRequired)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRadioNotrequired)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel7))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTemperature)
                                    .addComponent(txtHeight)
                                    .addComponent(txtPrescription, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtRespiratory, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPharmacy)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnBack)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(btnSubmit))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtPharmacyMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15)
                                .addGap(31, 31, 31)
                                .addComponent(comboPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(comboState, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combodrug, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboCity, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDrugName))))
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtRespiratory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMedication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnradioRequired)
                            .addComponent(btnRadioNotrequired))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMessage)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(comboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(comboState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(comboCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(comboPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(combodrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDrugName))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPharmacy)
                            .addComponent(txtPharmacyMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(86, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubmit)
                            .addComponent(btnBack))
                        .addGap(20, 20, 20))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBloodPressureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPressureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPressureActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        try
        {
        String labTest = null;
        String message = null;
        float weight = Float.parseFloat(txtWeight.getText());
        float height = Float.parseFloat(txtHeight.getText());
        float bloodPressure = Float.parseFloat(txtBloodPressure.getText());
        float respiratoryRate = Float.parseFloat(txtRespiratory.getText());
        float heartRate = Float.parseFloat(txtHeartRate.getText());
        float temperature = Float.parseFloat(txtTemperature.getText());
        String medication = txtMedication.getText();
        String prescription = txtPrescription.getText();
        String messagePharmacy=txtPharmacyMessage.getText();
        if (btnradioRequired.isSelected()) {
            labTest = "Require";
            message = txtMessage.getText();

        }
        if (btnRadioNotrequired.isSelected()) {
            labTest = "NotRequire";
        }

        if (medication.isEmpty() || prescription.isEmpty() || labTest == null || messagePharmacy.isEmpty()) {
            JOptionPane.showMessageDialog(null, "please enter values");
        }

        Encounter encounter = new Encounter();
        encounter.setDate(new Date());
        encounter.setDoctor(doctor);
        encounter.setPatient(patient);
        encounter.setDiagnosis(medication);
        encounter.getVitalSign().setBloodPressure(bloodPressure);
        encounter.getVitalSign().setHeartRate(heartRate);
        encounter.getVitalSign().setHeight(height);
        encounter.getVitalSign().setRespiratoryRate(respiratoryRate);
        encounter.getVitalSign().setTemperature(temperature);
        encounter.getVitalSign().setWeight(weight);
        encounter.getMedicineList().add(medication);

        if (labTest=="Require") {
            EncounterLabWorkRequest request = new EncounterLabWorkRequest();
            request.setMessage(message);
            request.setPatientMRN(patient.getPatientMRN());
            request.setPatientName(patient.getFirstName());
            request.setSender(doctor);
            request.setStatus("send to Lab Organization");
            request.setSenderEnterprise(enterprise);
            encounter.setLabWorkRequest(request);
            for (Organization org: enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof LabAssistantOrganization) {
                    org.getWorkQueue().getWorkRequestList().add(request);
                }
            }
            patient.getWorkQueue().getWorkRequestList().add(request);
            doctor.getWorkQueue().getWorkRequestList().add(request);
        }
        Enterprise pharmacyEnterprise=(Enterprise)comboPharmacy.getSelectedItem();
        if(pharmacyEnterprise==null)
        {
            JOptionPane.showMessageDialog(null, "please select value");
            return;
        }
        Drug drug=(Drug)combodrug.getSelectedItem();
        if(drug==null)
        {
            JOptionPane.showMessageDialog(null, "please select drug properly");
            return;
        }
        PharmacyWorkRequest phRequest=new PharmacyWorkRequest();
        phRequest.setDoctor(doctor);
        phRequest.setPatient(patient);
        phRequest.setEnterprise(enterprise);
        phRequest.setMessage(messagePharmacy);
        phRequest.setDrugSender(pharmacyEnterprise.getName());
        phRequest.setStatus("Sent to pharmacy");
        phRequest.setSendDrug(drug);
        encounter.setPhWorkRequest(phRequest);
        encounter.getPrescribedDrug().add(drug);
        patient.getWorkQueue().getWorkRequestList().add(phRequest);
        doctor.getWorkQueue().getWorkRequestList().add(phRequest);
        
        if(pharmacyEnterprise != null)
        {
            if(pharmacyEnterprise instanceof PharmacyEnterprise)
                {
                    PharmacyEnterprise phEnterprise=(PharmacyEnterprise)pharmacyEnterprise;
                    phEnterprise.getWorkQueue().getWorkRequestList().add(phRequest);
                }
        }
        
        
        if(enterprise instanceof HospitalEnterprise)
        {
            HospitalEnterprise hosEnterprise=(HospitalEnterprise)enterprise;
            hosEnterprise.getEncounterList().add(encounter);
        }
        if(enterprise instanceof ClinicEnterprise)
        {
            ClinicEnterprise clinicEnterprise=(ClinicEnterprise)enterprise;
            clinicEnterprise.getEncounterList().add(encounter);
        }
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "please enter proper values");
            return;
        }
        
        btnSubmit.setVisible(false);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnradioRequiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnradioRequiredActionPerformed
        // TODO add your handling code here:
        if (btnradioRequired.isSelected()) {
            txtMessage.setVisible(true);
            labelMessage.setVisible(true);
        }
    }//GEN-LAST:event_btnradioRequiredActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCountryActionPerformed
        // TODO add your handling code here:
        Network country=(Network)comboCountry.getSelectedItem();
        if(country != null)
        {
            populateStateCombo(country);
        }
    }//GEN-LAST:event_comboCountryActionPerformed

    private void comboStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStateActionPerformed
        // TODO add your handling code here:
        NetworkState state=(NetworkState)comboState.getSelectedItem();
        if(state != null)
        {
            populateCityCombo(state);
        }
    }//GEN-LAST:event_comboStateActionPerformed

    private void comboCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCityActionPerformed
        // TODO add your handling code here:
        NetworkCity city=(NetworkCity)comboCity.getSelectedItem();
        if(city != null)
        {
            populatePharmacyCombo(city);
        }
        
    }//GEN-LAST:event_comboCityActionPerformed

    private void comboPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPharmacyActionPerformed
        // TODO add your handling code here:
        PharmacyEnterprise phEnterprise=(PharmacyEnterprise)comboPharmacy.getSelectedItem();
        if(phEnterprise !=null)
        {
            populateComboDrug(phEnterprise);
        }
    }//GEN-LAST:event_comboPharmacyActionPerformed

    private void combodrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combodrugActionPerformed
        // TODO add your handling code here:
        Drug drug=(Drug)combodrug.getSelectedItem();
        if(drug!=null)
        {
            lblDrugName.setText(drug.getDrugName());
        }
    }//GEN-LAST:event_combodrugActionPerformed

    public void populateComboDrug(PharmacyEnterprise phEnterprise)
    {
        combodrug.removeAllItems();
        for(Drug drug:phEnterprise.getPharmacyDrugList())
            {
                if(drug.getDrugStatus().equals("Approved"))
                {
                    combodrug.addItem(drug);
                }
                
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnRadioNotrequired;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JRadioButton btnradioRequired;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboCity;
    private javax.swing.JComboBox comboCountry;
    private javax.swing.JComboBox comboPharmacy;
    private javax.swing.JComboBox comboState;
    private javax.swing.JComboBox combodrug;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelMessage;
    private javax.swing.JLabel labelPharmacy;
    private javax.swing.JLabel lblDrugName;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtMedication;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtPharmacyMessage;
    private javax.swing.JTextField txtPrescription;
    private javax.swing.JTextField txtRespiratory;
    private javax.swing.JTextField txtTemperature;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
