/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DoctorRole;

import Business.Doctor.Doctor;
import Business.EcoSystem;
import Business.Enterprise.ClinicEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Network.NetworkCity;
import Business.Network.NetworkState;
import Business.WorkQueue.EmergencyAssignWorkRequest;
import Business.WorkQueue.EmergencyEnquiryWorkRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import UserInterface.PatientRole.ReceivedCommunicationWorkRequestJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rekhajindal
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Doctor doctor;
    private ArrayList<Enterprise>enterpriseList;
    private EcoSystem system;
    
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DoctorWorkAreaJPanel(JPanel upc,Enterprise enterprise,Doctor doctor,EcoSystem system) {
        initComponents();
        this.userProcessContainer=upc;
        this.enterprise=enterprise;
        this.doctor=doctor;
        this.system=system;
        populateVoidEmergencyWorkRequestTable();
    }

    public void populateVoidEmergencyWorkRequestTable()
    {
        DefaultTableModel model=(DefaultTableModel)emergencyWorkRequestTable.getModel();
        model.setRowCount(0);
        for(WorkRequest request:doctor.getWorkQueue().getWorkRequestList())
        {
            if(request instanceof EmergencyAssignWorkRequest)
            {
                EmergencyAssignWorkRequest emergencyRequest=(EmergencyAssignWorkRequest)request;
                Object[]row=new Object[4];
                row[0]=emergencyRequest;
                row[1]=emergencyRequest.getPatientMRN();
                row[2]=emergencyRequest.getPatientName();
                row[3]=emergencyRequest.getSenderEnterprise();
                model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageworkRequest = new javax.swing.JButton();
        btnManageLabrequest = new javax.swing.JButton();
        btnDoctorPharmacyWorkRequest = new javax.swing.JButton();
        btnViewSentReferal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        emergencyWorkRequestTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSendEnquiry = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtmessage = new javax.swing.JTextField();
        btnManageEmergencyPatient = new javax.swing.JButton();
        btnreceivedCommunication = new javax.swing.JButton();

        btnManageworkRequest.setText("Manage Patient Work Request");
        btnManageworkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageworkRequestActionPerformed(evt);
            }
        });

        btnManageLabrequest.setText("Manage Lab Work Request");
        btnManageLabrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLabrequestActionPerformed(evt);
            }
        });

        btnDoctorPharmacyWorkRequest.setText("Manage Pharmacy Work Request");
        btnDoctorPharmacyWorkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorPharmacyWorkRequestActionPerformed(evt);
            }
        });

        btnViewSentReferal.setText("View Sent Refer work Request");
        btnViewSentReferal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSentReferalActionPerformed(evt);
            }
        });

        emergencyWorkRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Patient MRN", "Patient Name", "Enterprise Name"
            }
        ));
        jScrollPane1.setViewportView(emergencyWorkRequestTable);

        jLabel1.setText("List of Emergency Request");

        btnSendEnquiry.setText("Send Enquiry");
        btnSendEnquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEnquiryActionPerformed(evt);
            }
        });

        jLabel2.setText("Message");

        btnManageEmergencyPatient.setText("Manage Emergency Patient Details");
        btnManageEmergencyPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmergencyPatientActionPerformed(evt);
            }
        });

        btnreceivedCommunication.setText("View Received Communication");
        btnreceivedCommunication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreceivedCommunicationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnSendEnquiry))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageworkRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageLabrequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDoctorPharmacyWorkRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewSentReferal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageEmergencyPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnreceivedCommunication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSendEnquiry)
                .addGap(35, 35, 35)
                .addComponent(btnManageworkRequest)
                .addGap(18, 18, 18)
                .addComponent(btnManageLabrequest)
                .addGap(18, 18, 18)
                .addComponent(btnDoctorPharmacyWorkRequest)
                .addGap(18, 18, 18)
                .addComponent(btnViewSentReferal)
                .addGap(18, 18, 18)
                .addComponent(btnManageEmergencyPatient)
                .addGap(18, 18, 18)
                .addComponent(btnreceivedCommunication)
                .addGap(106, 106, 106))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageworkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageworkRequestActionPerformed
        // TODO add your handling code here:
        ManageWorkRequestJPanel panel=new ManageWorkRequestJPanel(userProcessContainer,enterprise,doctor,system.getNetworkList());
        userProcessContainer.add("ManagepatientworkRequest", panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageworkRequestActionPerformed

    private void btnManageLabrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLabrequestActionPerformed
        // TODO add your handling code here:
        ViewLabRequestJPanel panel=new ViewLabRequestJPanel(userProcessContainer,enterprise,doctor,system.getNetworkList());
        userProcessContainer.add("ManageLabworkRequest", panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageLabrequestActionPerformed

    private void btnDoctorPharmacyWorkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorPharmacyWorkRequestActionPerformed
        // TODO add your handling code here:
        ManageDoctorPharmacyWorkRequestJPanel panel=new ManageDoctorPharmacyWorkRequestJPanel(userProcessContainer,doctor,enterprise);
        userProcessContainer.add("ManagePharmacyworkRequest", panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDoctorPharmacyWorkRequestActionPerformed

    private void btnViewSentReferalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSentReferalActionPerformed
        // TODO add your handling code here:
        
        ViewSentReferRequestJPanel panel=new ViewSentReferRequestJPanel(userProcessContainer,doctor);
        userProcessContainer.add("ViewSentReferalPanel", panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewSentReferalActionPerformed

    private void btnSendEnquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEnquiryActionPerformed
        // TODO add your handling code here:
        int selectedRow=emergencyWorkRequestTable.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "please select a row");
            return;
        }
        WorkRequest request=(WorkRequest)emergencyWorkRequestTable.getValueAt(selectedRow,0);
        long patientMRN=(Long)emergencyWorkRequestTable.getValueAt(selectedRow, 1);
        Enterprise senderEnterprise=(Enterprise)emergencyWorkRequestTable.getValueAt(selectedRow,3);
        String message=txtmessage.getText();
        if(message.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "please enter the message");
        }
        EmergencyEnquiryWorkRequest enquiryRequest=new EmergencyEnquiryWorkRequest();
        enquiryRequest.setPatientMRN(patientMRN);
        enquiryRequest.setDoctor(doctor);
        enquiryRequest.setSenderEnterprise(senderEnterprise);
        enquiryRequest.setMessage(message);
        doctor.getWorkQueue().getWorkRequestList().add(enquiryRequest);
        for(Network network:system.getNetworkList())
        {
            for(NetworkState state:network.getNetworkStateList())
            {
                for(NetworkCity city:state.getNetworkCityList())
                {
                    for(Enterprise enterprise:city.getEnterpriseDirectory().getEnterpriseList())
                    {
                        if(enterprise instanceof HospitalEnterprise || enterprise instanceof ClinicEnterprise)
                        {
                            enterprise.getWorkQueue().getWorkRequestList().add(enquiryRequest);
                        }
                    }
                }
            }
        }
        doctor.getWorkQueue().getWorkRequestList().remove(request);
    }//GEN-LAST:event_btnSendEnquiryActionPerformed

    private void btnManageEmergencyPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmergencyPatientActionPerformed
        // TODO add your handling code here:
        ManageEmergencyPatientDetailsJPanel panel=new ManageEmergencyPatientDetailsJPanel(userProcessContainer,doctor);
        userProcessContainer.add("ManageEmergencyPatientPanel", panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageEmergencyPatientActionPerformed

    private void btnreceivedCommunicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreceivedCommunicationActionPerformed
        // TODO add your handling code here:
        WorkQueue doctorQueue=doctor.getWorkQueue();
        ReceivedCommunicationWorkRequestJPanel panel=new ReceivedCommunicationWorkRequestJPanel(userProcessContainer,doctorQueue);
        userProcessContainer.add("receivedCommunicationPaneldoctor", panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnreceivedCommunicationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoctorPharmacyWorkRequest;
    private javax.swing.JButton btnManageEmergencyPatient;
    private javax.swing.JButton btnManageLabrequest;
    private javax.swing.JButton btnManageworkRequest;
    private javax.swing.JButton btnSendEnquiry;
    private javax.swing.JButton btnViewSentReferal;
    private javax.swing.JButton btnreceivedCommunication;
    private javax.swing.JTable emergencyWorkRequestTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtmessage;
    // End of variables declaration//GEN-END:variables
}
