/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DoctorRole;

import Business.Doctor.Doctor;
import Business.Encounter.Encounter;
import Business.Enterprise.ClinicEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PharmacyCompanyEnterprise;
import Business.PharmaceuticalCompany.Drug;
import Business.WorkQueue.FeedbackToPharmaCompanyWorkRequest;
import Business.WorkQueue.PharmacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rekhajindal
 */
public class ManageDoctorPharmacyWorkRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Doctor doctor;
    private Enterprise enterprise;
    /**
     * Creates new form ManageDoctorPharmacyWorkRequestJPanel
     */
    public ManageDoctorPharmacyWorkRequestJPanel(JPanel upc,Doctor doctor,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=upc;
        this.doctor=doctor;
        this.enterprise=enterprise;
        hideControls();
        populateEnterpriseCombo();
    }

    public void hideControls()
    {
        txtMessage.setVisible(false);
        lblMessage.setVisible(false);
        btnSendRequest.setVisible(false);
        lblDrugID.setVisible(false);
        lblDrugName.setVisible(false);
        lbltxtDrugID.setVisible(false);
        lbltxtDrugname.setVisible(false);
    }
    public void populateEnterpriseCombo()
    {
        comboEnterprise.removeAllItems();
        for(Enterprise enterprise:doctor.getEnterpriseList())
        {
            comboEnterprise.addItem(enterprise);
        }
    }
    public void populatePharmacyWorkRequestTable(Enterprise enterprise)
    {
        DefaultTableModel model=(DefaultTableModel)DoctorPharmacyWorkRequest.getModel();
        model.setRowCount(0);
       

        if(enterprise instanceof HospitalEnterprise )
        {
            for(WorkRequest request:doctor.getWorkQueue().getWorkRequestList())
            {
                if(request instanceof PharmacyWorkRequest)
                {
                    PharmacyWorkRequest PhRequest=(PharmacyWorkRequest)request;
                        Object[]row=new Object[4];
                        row[0]=PhRequest;
                        row[1]=PhRequest.getPatient().getFirstName();
                        row[2]=PhRequest.getDrugSender();
                        row[3]=PhRequest.getStatus();
                        model.addRow(row);
                }
                
                    
                }
                
            }
            
        
        
         if(enterprise instanceof ClinicEnterprise )
        {
            for(WorkRequest request:doctor.getWorkQueue().getWorkRequestList())
            {
                if(request instanceof PharmacyWorkRequest)
                {
                    PharmacyWorkRequest PhRequest=(PharmacyWorkRequest)request;
                        Object[]row=new Object[4];
                        row[0]=PhRequest;
                        row[1]=PhRequest.getPatient().getFirstName();
                        row[2]=PhRequest.getDrugSender();
                        row[3]=PhRequest.getStatus();
                        model.addRow(row);
                }
                
                    
                }
                
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DoctorPharmacyWorkRequest = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        comboEnterprise = new javax.swing.JComboBox();
        labelOrganizationID = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnSendRequest = new javax.swing.JButton();
        btnfeedback = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblDrugName = new javax.swing.JLabel();
        lblDrugID = new javax.swing.JLabel();
        btnViewdrug = new javax.swing.JButton();
        lbltxtDrugID = new javax.swing.JLabel();
        lbltxtDrugname = new javax.swing.JLabel();

        jLabel1.setText("List of Pharmacy Request");

        DoctorPharmacyWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Patient Name", "Pharmacy Name", "Request Status"
            }
        ));
        jScrollPane1.setViewportView(DoctorPharmacyWorkRequest);

        jLabel2.setText("select Enterprise");

        comboEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEnterpriseActionPerformed(evt);
            }
        });

        labelOrganizationID.setText("jLabel3");

        btnSendRequest.setText("Send Request");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });

        btnfeedback.setText("Feedback to Pharmaceutical Company");
        btnfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfeedbackActionPerformed(evt);
            }
        });

        lblMessage.setText("Message");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblDrugName.setText("jLabel2");

        lblDrugID.setText("jLabel2");

        btnViewdrug.setText("View Drugs");
        btnViewdrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewdrugActionPerformed(evt);
            }
        });

        lbltxtDrugID.setText("Drug ID");

        lbltxtDrugname.setText("Drug Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(comboEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelOrganizationID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnBack)
                        .addGap(131, 131, 131)
                        .addComponent(btnSendRequest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnViewdrug, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnfeedback)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbltxtDrugname)
                            .addComponent(lbltxtDrugID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDrugID)
                            .addComponent(lblDrugName))
                        .addGap(417, 417, 417))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblMessage)
                .addGap(18, 18, 18)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOrganizationID))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDrugID))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnfeedback)
                            .addComponent(btnViewdrug))
                        .addGap(18, 18, 18)
                        .addComponent(lbltxtDrugID)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltxtDrugname)
                    .addComponent(lblDrugName))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMessage))
                        .addGap(18, 18, 18)
                        .addComponent(btnSendRequest)
                        .addGap(28, 28, 28)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEnterpriseActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise=(Enterprise)comboEnterprise.getSelectedItem();
        if(enterprise != null)
        {
            labelOrganizationID.setText(String.valueOf(enterprise.getOrganizationID()));
            populatePharmacyWorkRequestTable(enterprise);
            
        }
    }//GEN-LAST:event_comboEnterpriseActionPerformed

    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
        // TODO add your handling code here:
        int selectedrow=DoctorPharmacyWorkRequest.getSelectedRow();
        //        if(selectedrow < 0)
        //        {
            //            JOptionPane.showMessageDialog(null, "please select a row");
            //
            //        }
        String message=txtMessage.getText();
        WorkRequest request=(WorkRequest)DoctorPharmacyWorkRequest.getValueAt(selectedrow, 0);
        PharmacyWorkRequest phRequest=(PharmacyWorkRequest)request;
        Drug drug=phRequest.getSendDrug();
        PharmacyCompanyEnterprise phComEnterprise=(PharmacyCompanyEnterprise)drug.getManufacturingEnterprise();

        FeedbackToPharmaCompanyWorkRequest workRequest=new FeedbackToPharmaCompanyWorkRequest();
        workRequest.setMessage(message);
        workRequest.setDrug(drug);
        workRequest.setSender(doctor);
        phComEnterprise.getWorkQueue().getWorkRequestList().add(workRequest);
    }//GEN-LAST:event_btnSendRequestActionPerformed

    private void btnfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfeedbackActionPerformed
        // TODO add your handling code here:
        int selectedrow=DoctorPharmacyWorkRequest.getSelectedRow();
        if(selectedrow < 0)
        {
            JOptionPane.showMessageDialog(null, "please select a row");
            return;
        }
        txtMessage.setVisible(true);
        lblMessage.setVisible(true);
        btnSendRequest.setVisible(true);
    }//GEN-LAST:event_btnfeedbackActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewdrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewdrugActionPerformed
        // TODO add your handling code here:
        
        int selectedRow=DoctorPharmacyWorkRequest.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "please select a row");
            return;
        }
        WorkRequest request=(WorkRequest)DoctorPharmacyWorkRequest.getValueAt(selectedRow,0);
        PharmacyWorkRequest phRequest=(PharmacyWorkRequest)request;
        Drug drug=phRequest.getSendDrug();
        lblDrugID.setVisible(true);
        lblDrugName.setVisible(true);
        lbltxtDrugID.setVisible(true);
        lbltxtDrugname.setVisible(true);
        lblDrugID.setText(String.valueOf(drug.getDrugID()));
        lblDrugName.setText(drug.getDrugName());

    }//GEN-LAST:event_btnViewdrugActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DoctorPharmacyWorkRequest;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JButton btnViewdrug;
    private javax.swing.JButton btnfeedback;
    private javax.swing.JComboBox comboEnterprise;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelOrganizationID;
    private javax.swing.JLabel lblDrugID;
    private javax.swing.JLabel lblDrugName;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lbltxtDrugID;
    private javax.swing.JLabel lbltxtDrugname;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
