/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DoctorRole;

import Business.Doctor.Doctor;
import Business.Encounter.Encounter;
import Business.Enterprise.Enterprise;
import Business.Patient.Patient;
import Business.WorkQueue.EmergencyEnquiryWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rekhajindal
 */
public class ManageEmergencyPatientDetailsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Doctor doctor;
    private Enterprise enterprise;
    /**
     * Creates new form ManageEmergencyPatientDetailsJPanel
     */
    public ManageEmergencyPatientDetailsJPanel(JPanel upc,Doctor doctor) {
        initComponents();
        this.userProcessContainer=upc;
        this.doctor=doctor;
        //this.enterprise=enterprise;
        populatePateintDetailsTable();
        
    }

    public void populatePateintDetailsTable()
    {
        DefaultTableModel model=(DefaultTableModel)EmergencyPatientDetailsTable.getModel();
        model.setRowCount(0);
        for(WorkRequest request:doctor.getWorkQueue().getWorkRequestList())
        {
            if(request instanceof EmergencyEnquiryWorkRequest)
            {
                EmergencyEnquiryWorkRequest enqRequest=(EmergencyEnquiryWorkRequest)request;
                Object[]row=new Object[3];
                row[0]=enqRequest;
                row[1]=enqRequest.getPatientMRN();
                row[2]=enqRequest.getSenderEnterprise();
                model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmergencyPatientDetailsTable = new javax.swing.JTable();
        btnEncounterDetails = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        EncounterDetailsTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnViewEncounter = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        jLabel1.setText("List of Emeregency Patient Detail");

        EmergencyPatientDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Message", "Patient MRN", "Patient Enterprise"
            }
        ));
        jScrollPane1.setViewportView(EmergencyPatientDetailsTable);

        btnEncounterDetails.setText("Get Encounter Details");
        btnEncounterDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncounterDetailsActionPerformed(evt);
            }
        });

        EncounterDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "EncounterID", "Date of Encounter"
            }
        ));
        jScrollPane2.setViewportView(EncounterDetailsTable);

        jLabel2.setText("Encounter Details");

        btnViewEncounter.setText("View Encounter History");
        btnViewEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEncounterActionPerformed(evt);
            }
        });

        btnback.setText("<< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnback))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnViewEncounter))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btnEncounterDetails)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnEncounterDetails)
                .addGap(47, 47, 47)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewEncounter)
                .addGap(18, 18, 18)
                .addComponent(btnback)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncounterDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncounterDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow=EmergencyPatientDetailsTable.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"please select a row");
            return;
        }
        WorkRequest request=(WorkRequest)EmergencyPatientDetailsTable.getValueAt(selectedRow, 0);
        EmergencyEnquiryWorkRequest enqRequest=(EmergencyEnquiryWorkRequest)request;
        populateEncounterDetails(enqRequest);
    }//GEN-LAST:event_btnEncounterDetailsActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnViewEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEncounterActionPerformed
        // TODO add your handling code here:
        int selectedRow=EncounterDetailsTable.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "please select a row");
        }
        Encounter encounter=(Encounter)EncounterDetailsTable.getValueAt(selectedRow,0);
        ViewEncounterDetailsJPanel panel=new ViewEncounterDetailsJPanel(userProcessContainer, encounter);
        userProcessContainer.add("ViewEncounterforEmergencyPanel", panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewEncounterActionPerformed

    public void populateEncounterDetails(EmergencyEnquiryWorkRequest request)
    {
        DefaultTableModel model=(DefaultTableModel)EncounterDetailsTable.getModel();
        model.setRowCount(0);
        for(Encounter encounter:request.getEncounterList())
        {
            Object[]row=new Object[2];
            row[0]=encounter;
            row[1]=encounter.getDate();
            model.addRow(row);
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmergencyPatientDetailsTable;
    private javax.swing.JTable EncounterDetailsTable;
    private javax.swing.JButton btnEncounterDetails;
    private javax.swing.JButton btnViewEncounter;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
