/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DoctorRole;

import Business.Doctor.Doctor;
import Business.Encounter.Encounter;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.Network;
import Business.Network.NetworkCity;
import Business.Network.NetworkState;
import Business.Patient.Patient;
import Business.PharmaceuticalCompany.Drug;
import Business.WorkQueue.PharmacyWorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rekhajindal
 */
public class SendPrescriptionToPatientsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ArrayList<Network>networkList;
    private Encounter encounter;
    /**
     * Creates new form SendPrescriptionToPatientsJPanel
     */
    public SendPrescriptionToPatientsJPanel(JPanel upc,ArrayList<Network>networkList,Encounter encounter) {
        initComponents();
        this.userProcessContainer=upc;
        this.networkList=networkList;
        this.encounter=encounter;
        populateCountryCombo();
    }

    
    public void populateCountryCombo()
    {
        comboCountry.removeAllItems();
        for(Network country:networkList)
        {
            comboCountry.addItem(country);
        }
        
    }
    public void populateStateCombo(Network country)
    {
        comboState.removeAllItems();
        for(NetworkState state: country.getNetworkStateList())
        {
            comboState.addItem(state);
        }
    }
    
    public void populateCityCombo(NetworkState state)
    {
        comboCity.removeAllItems();
        for(NetworkCity city:state.getNetworkCityList())
        {
            comboCity.addItem(city);
        }
    }
    
    public void populatePharmacyCombo(NetworkCity city)
    {
        comboPharmacy.removeAllItems();
        for(Enterprise enterprise:city.getEnterpriseDirectory().getEnterpriseList())
        {
            if(enterprise instanceof PharmacyEnterprise)
            {
                comboPharmacy.addItem(enterprise);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        comboCity = new javax.swing.JComboBox();
        comboState = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        comboCountry = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        comboPharmacy = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        txtPharmacyMessage = new javax.swing.JTextField();
        labelPharmacy = new javax.swing.JLabel();
        btnSendPharmacy = new javax.swing.JButton();
        combodrug = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        lblDrugName = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();

        jLabel10.setText("Select Country");

        comboCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCityActionPerformed(evt);
            }
        });

        comboState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStateActionPerformed(evt);
            }
        });

        jLabel13.setText("Select City");

        comboCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCountryActionPerformed(evt);
            }
        });

        jLabel12.setText("Select State");

        comboPharmacy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPharmacyActionPerformed(evt);
            }
        });

        jLabel15.setText("List of Pharmacies");

        labelPharmacy.setText("Message for Pharmacy");

        btnSendPharmacy.setText("Send Request to Pharmacy");
        btnSendPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendPharmacyActionPerformed(evt);
            }
        });

        combodrug.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combodrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combodrugActionPerformed(evt);
            }
        });

        jLabel16.setText("Select Drug ");

        lblDrugName.setText("jLabel1");

        btnback.setText("<< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btnSendPharmacy))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel16)
                        .addGap(37, 37, 37)
                        .addComponent(combodrug, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDrugName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnback)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelPharmacy)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPharmacyMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel13))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(comboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(120, 120, 120)
                                            .addComponent(jLabel12))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(comboCity, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15)))
                                    .addGap(52, 52, 52)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(comboState, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(comboState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(comboCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(comboPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(combodrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrugName))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPharmacyMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPharmacy))
                .addGap(35, 35, 35)
                .addComponent(btnSendPharmacy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnback)
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCityActionPerformed
        // TODO add your handling code here:
        NetworkCity city=(NetworkCity)comboCity.getSelectedItem();
        if(city != null)
        {
            populatePharmacyCombo(city);
        }

    }//GEN-LAST:event_comboCityActionPerformed

    private void comboStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStateActionPerformed
        // TODO add your handling code here:
        NetworkState state=(NetworkState)comboState.getSelectedItem();
        if(state != null)
        {
            populateCityCombo(state);
        }
    }//GEN-LAST:event_comboStateActionPerformed

    private void comboCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCountryActionPerformed
        // TODO add your handling code here:
        Network country=(Network)comboCountry.getSelectedItem();
        if(country != null)
        {
            populateStateCombo(country);
        }
    }//GEN-LAST:event_comboCountryActionPerformed

    private void btnSendPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendPharmacyActionPerformed
        // TODO add your handling code here:
        String messageToPharmacy=txtPharmacyMessage.getText();
        if(messageToPharmacy.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "please enter message");
        }
        Enterprise enterprise=(Enterprise)comboPharmacy.getSelectedItem();
        if(enterprise ==null)
        {
            JOptionPane.showMessageDialog(null,"please select pharmacy");
            return;
        }
        Drug drug=(Drug)combodrug.getSelectedItem();
        if(drug==null)
        {
            JOptionPane.showMessageDialog(null, "please select drug properly");
            return;
        }
        Doctor doctor=encounter.getDoctor();
        Patient patient=encounter.getPatient();
        
        PharmacyWorkRequest phrequest=new PharmacyWorkRequest();
        phrequest.setDoctor(doctor);
        phrequest.setPatient(patient);
        phrequest.setEnterprise(encounter.getLabWorkRequest().getSenderEnterprise());
        phrequest.setMessage(messageToPharmacy);
        phrequest.setStatus("send to pharmacy");
        phrequest.setDrugSender(enterprise.getName());
        phrequest.setSendDrug(drug);
        doctor.getWorkQueue().getWorkRequestList().add(phrequest);
        patient.getWorkQueue().getWorkRequestList().add(phrequest);
        enterprise.getWorkQueue().getWorkRequestList().add(phrequest);
        encounter.getPrescribedDrug().add(drug);
        
    }//GEN-LAST:event_btnSendPharmacyActionPerformed

    private void comboPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPharmacyActionPerformed
        // TODO add your handling code here:
        PharmacyEnterprise phEnterprise=(PharmacyEnterprise)comboPharmacy.getSelectedItem();
        if(phEnterprise !=null)
        {
            populateComboDrug(phEnterprise);
        }
    }//GEN-LAST:event_comboPharmacyActionPerformed

    private void combodrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combodrugActionPerformed
        // TODO add your handling code here:
        Drug drug=(Drug)combodrug.getSelectedItem();
        if(drug!=null)
        {
            lblDrugName.setText(drug.getDrugName());
        }
    }//GEN-LAST:event_combodrugActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed

    public void populateComboDrug(PharmacyEnterprise phEnterprise)
    {
        combodrug.removeAllItems();
        for(Drug drug:phEnterprise.getPharmacyDrugList())
            {
                if(drug.getDrugStatus().equals("Approved"))
                {
                    combodrug.addItem(drug);
                }
                
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendPharmacy;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox comboCity;
    private javax.swing.JComboBox comboCountry;
    private javax.swing.JComboBox comboPharmacy;
    private javax.swing.JComboBox comboState;
    private javax.swing.JComboBox combodrug;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel labelPharmacy;
    private javax.swing.JLabel lblDrugName;
    private javax.swing.JTextField txtPharmacyMessage;
    // End of variables declaration//GEN-END:variables
}
