/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DoctorRole;

import Business.Encounter.Encounter;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rekhajindal
 */
public class ViewEncounterHistoryJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ArrayList<Encounter>encounterList;
    /**
     * Creates new form ViewEncounterHistoryJPanel
     */
    public ViewEncounterHistoryJPanel(JPanel upc,ArrayList<Encounter>list) {
        initComponents();
        this.userProcessContainer=upc;
        this.encounterList=list;
        populateEncounterDetailsTable();
    }

    public void populateEncounterDetailsTable()
    {
        DefaultTableModel model=(DefaultTableModel)encounterDetailsJTable.getModel();
        model.setRowCount(0);
        for(Encounter encounter:encounterList)
        {
            Object[]row=new Object[2];
            row[0]=encounter;
            row[1]=encounter.getDate();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        encounterDetailsJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnViewEncounterList = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        encounterDetailsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Encounter ID", "Date"
            }
        ));
        jScrollPane1.setViewportView(encounterDetailsJTable);

        jLabel1.setText("List of Encounter ");

        btnViewEncounterList.setText("View Encounter Details");
        btnViewEncounterList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEncounterListActionPerformed(evt);
            }
        });

        btnback.setText("<< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnViewEncounterList))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnback)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnViewEncounterList)
                .addGap(151, 151, 151)
                .addComponent(btnback)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewEncounterListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEncounterListActionPerformed
        // TODO add your handling code here:
        int selectedRow=encounterDetailsJTable.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "please select a row");
            return;
        }
        Encounter encounter=(Encounter)encounterDetailsJTable.getValueAt(selectedRow,0);
        ViewEncounterDetailsJPanel panel=new ViewEncounterDetailsJPanel(userProcessContainer,encounter);
        userProcessContainer.add("ViewEncounterDetails", panel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewEncounterListActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewEncounterList;
    private javax.swing.JButton btnback;
    private javax.swing.JTable encounterDetailsJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
