/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PharmaceuticalCompanyRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PharmaceuticalCompanyOrganization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rekhajindal
 */
public class DrugAdminOrganizationWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessConatiner;
    private Enterprise enterprise;
    private Organization organization;
    private EcoSystem system;
    /**
     * Creates new form DrugAdminOrganizationWorkAreaJPanel
     */
    public DrugAdminOrganizationWorkAreaJPanel(JPanel upc, Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.userProcessConatiner=upc;
        this.enterprise=enterprise;
        this.system=system;
    }

    public void getOrganization()
    {
        for(Organization org:enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(org instanceof PharmaceuticalCompanyOrganization)
            {
                organization=(PharmaceuticalCompanyOrganization)org;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageDrugs = new javax.swing.JButton();
        btnManageWorkRequest = new javax.swing.JButton();

        btnManageDrugs.setText("Manage Drugs");
        btnManageDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDrugsActionPerformed(evt);
            }
        });

        btnManageWorkRequest.setText("Manage Work Request");
        btnManageWorkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageWorkRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageWorkRequest)
                    .addComponent(btnManageDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(232, 232, 232))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnManageDrugs)
                .addGap(37, 37, 37)
                .addComponent(btnManageWorkRequest)
                .addGap(122, 122, 122))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDrugsActionPerformed
        // TODO add your handling code here:
        ManageDrugJPanel panel =new ManageDrugJPanel(userProcessConatiner,organization,enterprise,system);
        userProcessConatiner.add("ManageDrugPanel", panel);
        CardLayout layout=(CardLayout)userProcessConatiner.getLayout();
        layout.next(userProcessConatiner);
    }//GEN-LAST:event_btnManageDrugsActionPerformed

    private void btnManageWorkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageWorkRequestActionPerformed
        // TODO add your handling code here:
        ManageWorkRequestJPanel panel=new ManageWorkRequestJPanel(userProcessConatiner,enterprise);
        userProcessConatiner.add("ManageWorkRequestPanel", panel);
        CardLayout layout=(CardLayout)userProcessConatiner.getLayout();
        layout.next(userProcessConatiner);
    }//GEN-LAST:event_btnManageWorkRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDrugs;
    private javax.swing.JButton btnManageWorkRequest;
    // End of variables declaration//GEN-END:variables
}
