/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PharmaceuticalCompanyRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyCompanyEnterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.PharmaceuticalCompany.Drug;
import Business.WorkQueue.DrugCallBackRequestWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rekhajindal
 */
public class DrugCallBackJPanel extends javax.swing.JPanel {

    private JPanel userprocessContainer;
    private Enterprise enterprise;
    /**
     * Creates new form DrugCallBackJPanel
     */
    public DrugCallBackJPanel(JPanel upc,Enterprise enterprise) {
        initComponents();
        this.userprocessContainer=upc;
        this.enterprise=enterprise;
        populateDrugTable();
    }

    public void populateDrugTable()
    {
        DefaultTableModel model=(DefaultTableModel)DrugDetailsTable.getModel();
        model.setRowCount(0);
        if(enterprise instanceof PharmacyCompanyEnterprise)
        {
            PharmacyCompanyEnterprise phEnterprise=(PharmacyCompanyEnterprise)enterprise;
                for(Drug drug:phEnterprise.getDrugList())
                {
                    if(drug.getDrugStatus().equalsIgnoreCase("Approved"))
                    {
                        Object[]row=new Object[3];
                        row[0]=drug;
                        row[1]=drug.getDrugName();
                        row[2]=drug.getDrugStatus();
                        model.addRow(row);
                    }
                }
    }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DrugDetailsTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setText("Select Drug");

        DrugDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "Drug Status"
            }
        ));
        jScrollPane1.setViewportView(DrugDetailsTable);

        jLabel2.setText("Message");

        btnRequest.setText("Send Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(46, 46, 46)
                                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(btnRequest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnBack)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166)
                .addComponent(btnRequest)
                .addGap(33, 33, 33)
                .addComponent(btnBack)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow=DrugDetailsTable.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null, "please select a row");
            return;
        }
        Drug drug=(Drug)DrugDetailsTable.getValueAt(selectedRow, 0);
        drug.setDrugStatus("CallBack");
        String message=txtMessage.getText();
        if(message.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "please enter the message");
            return;
        }
        DrugCallBackRequestWorkRequest callBackRequest=new DrugCallBackRequestWorkRequest();
        callBackRequest.setDrug(drug);
        callBackRequest.setSenderEnterprise(enterprise);
        callBackRequest.setMessage(message);
        PharmacyCompanyEnterprise phComEnterprise=(PharmacyCompanyEnterprise)enterprise;
        for(Enterprise enterprise:phComEnterprise.getPharmacyList())
        {
            if(enterprise instanceof PharmacyEnterprise)
            {
                PharmacyEnterprise phEnterprise=(PharmacyEnterprise)enterprise;
                phEnterprise.getWorkQueue().getWorkRequestList().add(callBackRequest);
                
            }
        }
        phComEnterprise.getWorkQueue().getWorkRequestList().add(callBackRequest);
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userprocessContainer.remove(this);
        CardLayout layout=(CardLayout)userprocessContainer.getLayout();
        layout.previous(userprocessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DrugDetailsTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
